services:
  postgres18-mssql:
    build: .
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: sqlserver
      POSTGRES_PASSWORD: mssql
      POSTGRES_USER: mssql

  mssqlserver-2019:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y 
      MSSQL_SA_PASSWORD: Welcome1 
        
